# Pre-commit configuration
# Tool-specific settings (line length, rules, etc.) are defined in pyproject.toml
# This file only defines which hooks to run and their versions

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        stages: [pre-commit]
    -   id: end-of-file-fixer
        stages: [pre-commit]
    -   id: check-yaml
        stages: [pre-commit]
    -   id: check-added-large-files
        stages: [pre-commit]
    -   id: debug-statements
        stages: [pre-commit]
    -   id: check-merge-conflict
        stages: [pre-commit]
    -   id: check-ast
        stages: [pre-commit]
    -   id: check-json
        stages: [pre-commit]
    -   id: check-toml
        stages: [pre-commit]
    -   id: detect-private-key
        stages: [pre-commit]
    -   id: mixed-line-ending
        args: [--fix=lf]
        stages: [pre-commit]

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]

    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

    -   id: ruff
        name: ruff
        entry: poetry run ruff check --fix
        language: system
        types: [python]

    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]

    -   id: pyright
        name: pyright
        entry: poetry run pyright
        language: system
        types: [python]

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
        exclude: coverage\.xml
    -   id: remove-tabs
        args: [--whitespaces-count, '4']
        exclude: coverage\.xml

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm
        -   mdformat-black

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []
